version: '3.2'
services:
  mqtt:
    image: 'eclipse-mosquitto:latest'
    ports:
     - '1883:1883'
     - '9001:9001'
  nodered:
    image: 'nodered/node-red-docker:latest'
    volumes:
     - ./red/data:/data
     - ./red/public:/home/nol/node-red-static
    ports:
     - '1880:1880'
    depends_on:
     - 'mqtt'
     - 'mongo'
  mongo:
    image: 'mongo:latest'
    ports:
     - '27017:27017'
    
